[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
    functions = "functions"
[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"